[gateway]
url = "https://api.fil.cztec.com/fildr-miner"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiI1ODkxNTEiLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJlYWxfbmFtZSI6ImFkbWluIiwiYXZhdGFyIjoiIiwiYXV0aG9yaXRpZXMiOlsiYWRtaW4iXSwiY2xpZW50X2lkIjoibWluZXIiLCJyb2xlX25hbWUiOiJhZG1pbiIsImxpY2Vuc2UiOiJwb3dlcmVkIGJ5IGJsYWRleCIsInBvc3RfaWQiOiIxMjgyNTczODg1MjM1MzA2NDk4IiwidXNlcl9pZCI6IjEyODI1NzM4ODU0MzY3NjAwNjUiLCJyb2xlX2lkIjoiMTI4MjU3Mzg4MDk2NTUwNTAyNiIsInNjb3BlIjpbImFsbCJdLCJuaWNrX25hbWUiOiJhZG1pbiIsIm9hdXRoX2lkIjoiIiwiZXhwIjoxOTA1NjY1NTIyLCJkZXB0X2lkIjoiMTI4MjU3Mzg4NTE0NzIyNjExMyIsImp0aSI6ImRjYzA0NGFmLWVhZTMtNGZmOC04MjVjLWQzOTc0ZjZlMjQ1MiIsImFjY291bnQiOiJhZG1pbiJ9.eo6t5h-Hfcvb9vs6IPCQUw3PvdIXBsSWCz5A_o09-8E"
instance = "hostname1"
evaluation = 5

